# Generated by Django 3.1.4 on 2021-03-03 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkin_date', models.DateField(verbose_name='data de checkin')),
                ('checkout_date', models.DateField(verbose_name='data de checkout')),
            ],
        ),
    ]
