# Generated by Django 3.1.5 on 2021-03-07 04:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0002_auto_20210307_0005'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='hotels',
        ),
        migrations.AddField(
            model_name='reservation',
            name='hotel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reservation.hotel', verbose_name='Hotel'),
        ),
    ]
